
DROP TABLE IF EXISTS json_standard;
CREATE TABLE json_standard (
	col1 JSON)
WITH (appendonly = TRUE)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_zlib1;
CREATE TABLE json_zlib1 (
	col1 JSON)
WITH (appendonly=true, COMPRESSTYPE=zlib, COMPRESSLEVEL=1)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_zlib5;
CREATE TABLE json_zlib5 (
	col1 JSON)
WITH (appendonly=true, COMPRESSTYPE=zlib, COMPRESSLEVEL=5)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_zlib9;
CREATE TABLE json_zlib9 (
	col1 JSON)
WITH (appendonly=true, COMPRESSTYPE=zlib, COMPRESSLEVEL=9)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_quicklz;
CREATE TABLE json_quicklz (
	col1 JSON)
WITH (appendonly=true, COMPRESSTYPE=quicklz)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_rle1;
CREATE TABLE json_rle1 (
	col1 JSON ENCODING (COMPRESSTYPE=RLE_TYPE, COMPRESSLEVEL=1))
WITH (appendonly=TRUE, orientation=COLUMN)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_rle2;
CREATE TABLE json_rle2 (
	col1 JSON ENCODING (COMPRESSTYPE=RLE_TYPE, COMPRESSLEVEL=2))
WITH (appendonly=TRUE, orientation=COLUMN)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_rle3;
CREATE TABLE json_rle3 (
	col1 JSON ENCODING (COMPRESSTYPE=RLE_TYPE, COMPRESSLEVEL=3))
WITH (appendonly=TRUE, orientation=COLUMN)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_rle4;
CREATE TABLE json_rle4 (
	col1 JSON ENCODING (COMPRESSTYPE=RLE_TYPE, COMPRESSLEVEL=4))
WITH (appendonly=TRUE, orientation=COLUMN)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_quicklz_blocksize8K;
CREATE TABLE json_quicklz_blocksize8K (
	col1 JSON ENCODING (COMPRESSTYPE=quicklz, BLOCKSIZE=8192))
WITH (appendonly=TRUE, orientation=COLUMN)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_quicklz_blocksize16K;
CREATE TABLE json_quicklz_blocksize16K (
	col1 JSON ENCODING (COMPRESSTYPE=quicklz, BLOCKSIZE=16384))
WITH (appendonly=TRUE, orientation=COLUMN)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_quicklz_blocksize32K;
CREATE TABLE json_quicklz_blocksize32K (
	col1 JSON ENCODING (COMPRESSTYPE=quicklz, BLOCKSIZE=32768))
WITH (appendonly=TRUE, orientation=COLUMN)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_zlib1_blocksize8K;
CREATE TABLE json_zlib1_blocksize8K (
	col1 JSON ENCODING (COMPRESSTYPE=zlib, COMPRESSLEVEL=1, BLOCKSIZE=8192))
WITH (appendonly=TRUE, orientation=COLUMN)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_zlib1_blocksize16K;
CREATE TABLE json_zlib1_blocksize16K (
	col1 JSON ENCODING (COMPRESSTYPE=zlib, COMPRESSLEVEL=1, BLOCKSIZE=16384))
WITH (appendonly=TRUE, orientation=COLUMN)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_zlib1_blocksize32K;
CREATE TABLE json_zlib1_blocksize32K (
	col1 JSON ENCODING (COMPRESSTYPE=zlib, COMPRESSLEVEL=1, BLOCKSIZE=32768))
WITH (appendonly=TRUE, orientation=COLUMN)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_rle4_blocksize8K;
CREATE TABLE json_rle4_blocksize8K (
	col1 JSON ENCODING (COMPRESSTYPE=RLE_TYPE, COMPRESSLEVEL=4, BLOCKSIZE=8192))
WITH (appendonly=TRUE, orientation=COLUMN)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_rle4_blocksize16K;
CREATE TABLE json_rle4_blocksize16K (
	col1 JSON ENCODING (COMPRESSTYPE=RLE_TYPE, COMPRESSLEVEL=4, BLOCKSIZE=16384))
WITH (appendonly=TRUE, orientation=COLUMN)
DISTRIBUTED RANDOMLY;

DROP TABLE IF EXISTS json_rle4_blocksize32K;
CREATE TABLE json_rle4_blocksize32K (
	col1 JSON ENCODING (COMPRESSTYPE=RLE_TYPE, COMPRESSLEVEL=4, BLOCKSIZE=32768))
WITH (appendonly=TRUE, orientation=COLUMN)
DISTRIBUTED RANDOMLY;
